sudo: no
dist: stretch
group: edge
language: node_js
node_js:
  - 10

script:
  - >
    go version &&
    cd snippets &&
    go test &&
    cd .. &&
    projRoot=$(pwd) &&
    cd /tmp/ &&
    wget --no-verbose 'https://github.com/client9/misspell/releases/download/v0.3.4/misspell_0.3.4_linux_64bit.tar.gz' -O misspell.tar.gz &&
    tar zxf misspell.tar.gz &&
    cd $projRoot &&
    git clean -dffxn &&
    git ls-files -co --exclude-standard | xargs /tmp/misspell --error &&
    cd pages-generator &&
    npm install &&
    ./init.js &&
    cd .. &&
    cp -r dist /tmp/dist &&
    rm -rf * &&
    cp -r /tmp/dist/* . &&
    echo -n codejam.maowtm.org > CNAME

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: false
  on:
    branch: master
